name: "tomtom-api-coding-challenge"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../../tomtom-api-coding-challenge:/workspaces/tomtom-api-coding-challenge:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    depends_on:
      selenium:
        condition: service_healthy

  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4444/wd/hub/status || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
